### ISSUE TITLE
Sort diffs by size

### ISSUE THREAD

**Issue by eerhardt** [MichalStrehovsky/sizoscope#1]
I'd like to sort this view by size:

![image](https://user-images.githubusercontent.com/8291187/233187877-329cca3b-ab8f-4109-a766-f524077fc0e9.png)

With some of the numbers in `B` and some in `kB`, it is hard to quickly figure out which assembly is contributing to the most size.

**Comment by MichalStrehovsky** [comment]
Fixed in 1.0.1.
