### ISSUE TITLE
 The required file does not appear after compilation.

### ISSUE THREAD

**Issue by dadavadd** [MichalStrehovsky/sizoscope#12]
![image](https://github.com/MichalStrehovsky/sizoscope/assets/111659964/c15a2ecf-b558-4698-a0e2-5c334742bab2)
After compilation, the ".mstat" file does not appear in the specified directory.

![image](https://github.com/MichalStrehovsky/sizoscope/assets/111659964/45e230e7-9b44-4f2d-998c-ed17b6a44ac7)

**Comment by MichalStrehovsky** [comment]
The directory is obj, not bin
